---
- name: Create wallpaper directory
  become: true
  file:
    path: /usr/local/share/wallpaper
    state: directory

- name: Download wallpaper for desktop
  become: true
  get_url:
    url: https://images.wallpaperscraft.com/image/single/house_fairy_tale_art_101615_1920x1080.jpg
    dest: /usr/local/share/wallpaper/house_fairy_tale_art_101615_1920x1080.jpg

- name: Set wallpaper using feh
  become: true
  shell: feh --bg-scale /usr/local/share/wallpaper/house_fairy_tale_art_101615_1920x1080.jpg

- name: Add wallpaper setting to i3 config
  lineinfile:
    path: /home/{{ local_user }}/.config/i3/config
    state: present
    line: "exec_always --no-startup-id feh --no-fehbg --bg-scale /usr/local/share/wallpaper/house_fairy_tale_art_101615_1920x1080.jpg &"
    regexp: "^exec_always --no-startup-id feh --no-fehbg --bg-scale /usr/local/share/wallpaper/house_fairy_tale_art_101615_1920x1080.jpg &"

- name: Download wallpaper for i3lock
  become: true
  get_url:
    url: https://images.wallpaperscraft.com/image/single/mask_neon_anonymous_180568_1920x1080.jpg
    dest: /usr/local/share/wallpaper/i3lock.jpg