---

- name: enable module-switch-on-connect for pulseaudio
  become: true
  lineinfile:
    path: /etc/pulse/default.pa
    line: "load-module module-switch-on-connect ignore_virtual=no"
    regexp: "load-module module-switch-on-connect.*"
