---
- name: Setup setxkbmap options in .profile
  lineinfile:
    path: "{{ local_home }}/.profile"
    state: present
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - { line: 'setxkbmap -option grp:shifts_toggle', regexp: '^setxkbmap -option grp:shifts_toggle' }
    - { line: 'setxkbmap -layout us,ru', regexp: '^setxkbmap -layout us,ru' }
