---

- name: setup udevmon
  become: yes
  blockinfile:
    path: /etc/interception/udevmon.d/caps2esc.yaml
    create: true
    block: |
      - JOB: "intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE"
        DEVICE:
          EVENTS:
            EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
- name: enable udevmon
  systemd:
    name: udevmon
    enabled: yes
    state: started
