---
- name: Setup udevmon configuration
  become: yes
  blockinfile:
    path: /etc/interception/udevmon.d/caps2esc.yaml
    create: true
    block: |
      - JOB: "intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE"
        DEVICE:
          EVENTS:
            EV_KEY: [KEY_CAPSLOCK, KEY_ESC]

- name: Enable and start udevmon service
  become: yes
  systemd:
    name: udevmon
    enabled: yes
    state: started