---
- name: Yay checkout
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '{{ yay_source_directory }}'

- name: Build and install yay
  command:
    chdir: '{{ yay_source_directory }}'
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay