- hosts: 127.0.0.1
  collections:
    - kewlfft.aur
  tasks:
    - name: install pacman packages
      include_tasks: playbooks/pacman_packages.yml
    - name: install aur packages
      include_tasks: playbooks/aur_packages.yml
    - name: install sdkman
      shell: "curl -s 'https://get.sdkman.io' | bash"
    - name: install antigen
      become: true
      shell: "curl -L git.io/antigen > /usr/local/bin/antigen.zsh"
    - name: enable docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: setup sudo without password
      become: true
      lineinfile:
        path: /etc/sudoers.d/irasikhin
        create: true
        line: "irasikhin ALL=(ALL) NOPASSWD: ALL"
    - name: setup udevmon
      include_tasks: playbooks/udevmon.yml
    - name: setup byobu
      include_tasks: playbooks/byobu.yml
    - name: setup headsets
      include_tasks: playbooks/headset.yml
    #    - name: setup background
    #      include_tasks: playbooks/background.yml
    - name: setxkbmap
      include_tasks: playbooks/setup_setxkbmap.yml
