- hosts: 127.0.0.1
  collections:
    - kewlfft.aur

  tasks:
    # Install Packages
    - name: Install pacman packages
      include_tasks: playbooks/pacman_packages.yml

    - name: Install AUR packages
      include_tasks: playbooks/aur_packages.yml

    # Setup SDKs and Tools
    - name: Install SDKMAN
      shell: "curl -s 'https://get.sdkman.io?rcupdate=false' | bash"

    - name: Install Antigen
      become: true
      shell: "curl -L git.io/antigen > /usr/local/bin/antigen.zsh"

    # System Services
    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # User Configuration
    - name: Setup sudo without password
      become: true
      lineinfile:
        path: "/etc/sudoers.d/{{ local_user }}"
        create: true
        line: "{{ local_user }} ALL=(ALL) NOPASSWD: ALL"

    # Additional Configurations
    - name: Setup udevmon
      include_tasks: playbooks/udevmon.yml

    - name: Setup Byobu
      include_tasks: playbooks/byobu.yml

    - name: Setup headsets
      include_tasks: playbooks/headset.yml

    # Keyboard Layout
    - name: Configure keyboard layout with setxkbmap
      include_tasks: playbooks/setup_setxkbmap.yml

    # Optional: Setup background (uncomment to use)
    # - name: Setup background
    #   include_tasks: playbooks/background.yml
