- hosts: 127.0.0.1
  roles:
    - kewlfft.aur
  tasks:
    - name: install pacman packages
      include: playbooks/pacman_packages.yml
    - name: install aur packages
      include: playbooks/aur_packages.yml
    - name: install space vim
      shell: "curl -sLf https://spacevim.org/install.sh | bash"
    - name: install antigen
      become: true
      shell: "curl -L git.io/antigen > /usr/local/bin/antigen.zsh"
    - name: enable docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: setup sudo without password
      become: true
      lineinfile:
        path: /etc/sudoers.d/irasikhin
        create: true
        line: "irasikhin ALL=(ALL) NOPASSWD: ALL"
    - name: setup udevmon
      include: playbooks/udevmon.yml
    - name: setup byobu
      include: playbooks/byobu.yml
    - name: setup headsets
      include: playbooks/headset.yml