- hosts: all
  tasks:
    - name: install pacman packages
      become: yes
      pacman:
        name: stow,curl,git,tree,stow,yay,pulseaudio-alsa,pulseaudio-bluetooth,xbindkeys,bluez-utils,scala
        state: present
    - name: install ansible-aur
      git:
        repo: https://github.com/kewlfft/ansible-aur.git
        dest: ~/.ansible/plugins/modules/aur
    - name: create aur_builder
      become: true
      user: name=aur_builder
    - name: add aur_builder to sudoers
      become: true
      lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes
    - name: install yay packages
      become: true
      become_user: aur_builder
      aur:
        use: yay
        skip_installed: true
        name:
          - i3status-rust
          - jdk
          - scala
          - sbt
          - antibody
          - vlc-git
          - groovy
          - maven
          - gradle
          - slack-desktop
          - command-not-found
          - git-extras
          - python-cookiecutter
          - atlassian-jira
          - pass-git
          - grip
          - buku
          - cloc
          - marker
          - aerc
          - lazydocker
          - exa
          - cointop
          - fselect

    # Apache Pulsar
    - name: download pulsar
      get_url:
        url: https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.4.2/apache-pulsar-2.4.2-bin.tar.gz
        dest: ~/work/app/pulsar.tar.gz
    - name: create directory
      file:
        path: ~/work/app/pulsar
        state: directory
    - name: unarchive pulsar
      unarchive:
        src: ~/work/app/pulsar.tar.gz
        dest: ~/work/app/pulsar
        extra_opts: [--strip-components=1]
