name: Ansible Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: archlinux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arch Linux environment
        uses: larrabee/archlinux-github-action@v1

      - name: Install Ansible and Run Script
        run: |
          sudo pacman --noconfirm -Syu ansible
          ./install.sh