name: Ansible Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: pacman --noconfirm -Sy python python-pip ansible-core ansible

      - name: Add venv
        run: python -m venv ./venv

      - name: Use venv
        run: source ./venv/bin/activate

      - name: Install ansible-devel
        run: python3 -m pip install https://github.com/ansible/ansible/archive/devel.tar.gz

      - name: Run Script
        run: bash ${GITHUB_WORKSPACE}/install.sh