name: Ansible Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-20240714.0.246936

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: pacman --noconfirm -Sy ansible-core ansible

      - name: Run Script
        run: bash ${GITHUB_WORKSPACE}/install.sh