name: Ansible Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Arch Linux environment
#        uses: heyhusen/archlinux-package-action@v2
#
      - name: Install Ansible and Run Script
        run: |
          pacman --noconfirm -Syu ansible
          echo '1'
          ls
          echo '2'
          ls ../
          ../install.sh